# Generated by Django 3.2.8 on 2021-11-03 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisor',
            name='profile_pic',
            field=models.ImageField(blank='True', null='True', upload_to=''),
            preserve_default='True',
        ),
    ]
